language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
sudo: enabled
dist: trusty
group: travis_lts
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - g++-6
      - g++-7
      - make
      - cmake
      - libboost-all-dev
      - swig3.0
env:
  - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
  - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
before_install:
  - eval "${MATRIX_EVAL}"
  - sudo ln -s /usr/bin/swig /usr/bin/swig3.0
install:
  - pip install setuptools
script:
  - bash build_linux.sh
