language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
root: required
dist: bionic
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - g++-8
      - g++-9
      - make
      - cmake
      - libboost-all-dev
      - swig
env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
  - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
  - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
before_install:
  - eval "${MATRIX_EVAL}"
install:
  - pip install setuptools
script:
  - bash build_linux.sh
