language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
sudo: enabled
dist: trusty
group: travis_lts
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - make
            - cmake
            - libboost-all-dev
            - swig
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - make
            - cmake
            - libboost-all-dev
            - swig
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - make
            - cmake
            - libboost-all-dev
            - swig
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
before_install:
  - eval "${MATRIX_EVAL}"
install:
  - pip install setuptools
script:
  - bash build_linux.sh
